### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by bd808** [jaxxstorm/puppet-kubeadm#16]
I found this comment in a source file `Copyright 2018 Lee Briggs, unless otherwise noted.`, but do not see a clear license applied to explain how use of that copyright is granted to others. https://choosealicense.com/ has some helpful information on selecting and applying an Open Source license to a software project. https://choosealicense.com/no-permission/ explains the case of unlicensed code:
> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

**Comment by jaxxstorm** [comment]
Thanks for spotting this, I added the MIT license. Hope this is useful!
